spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=daniel2
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.root=INFO
logging.level.com.miapp=DEBUG
logging.file.name=logs/academia.log